---
title: "model 7"
output: html_document
date: "2024-07-09"
---

# model 7 - model 6 but linear probability model, use other military variable

```{r setup, include=FALSE}
library(haven)
library(ltm)
library(tidyverse)
```

## military

```{r}
data <- read.csv("~/Documents/research/clean_mali_data.csv")

data$Q29B[data$Q29B == 9] <- NA
data$Q29B[data$Q29B == 5] <- NA

print(table(data$Q29B))

data$military <- ifelse(data$Q29B %in% c(1, 2), 0,
                        ifelse(data$Q29B %in% c(3, 4), 1, NA))

print(table(data$military))

na.omit(data) %>%
  ggplot(aes(x = factor(Q29B))) +
  geom_bar() +
  scale_x_discrete(labels = c("1" = "1 - Strongly Agree with\nStatement 1", "2" = "2 - Agree With\n Statement 1", "3" = "3 - Agree With\n Statement 2", "4" = "4 - Strongly Agree with\nStatement 2")) +
  coord_flip() +
  labs(title = "Distribution of Support for Military Intervention in Mali",
       x = "Response",
       y = "Frequency")
```

## corruption

```{r}
data$Q38A[data$Q38A == 8] <- NA
data$Q38A[data$Q38A == 9] <- NA

data$Q38B[data$Q38B == 8] <- NA
data$Q38B[data$Q38B == 9] <- NA

data$Q38F[data$Q38F == 8] <- NA
data$Q38F[data$Q38F == 9] <- NA

data$corrupt = data$Q38A + data$Q38B + data$Q38F

# na.omit(data) %>%
#   ggplot(aes(x = Q38A)) +
#   geom_bar() +
#   scale_x_discrete(labels = c("1" = "Strongly Agree with Statement 1", "2" = "Legislative", "3" = "Judicial", "4" = "Strongly Agree with Statement")) +
#   theme_minimal()

# na.omit(data) %>% 
#   ggplot(aes(x = Q38A)) +
#   geom_bar(stat = "identity") 
isolated_data <- data[, c("Q38A", "Q38B", "Q38F")]

# table(na.omit(isolated_data$Q38A))
# # Reshape the isolated data to long format
# da <- pivot_longer(isolated_data, cols = everything(), 
#                                    names_to = "Category", values_to = "Value")

# data_long <- reshape2::melt(da, id.vars = "Category")

# ggplot(da, aes(x = factor(Category), y = Value, fill = factor(Value))) +
#   geom_bar(stat = "identity", position = "stack") +
#   labs(x = "Government Branches", y = "Percentage", 
#        title = "Distribution of Perceived Corruption in Mali Government Branches") +
#   scale_fill_manual(labels = c("3", "2", "1", "0"), 
#                       values = c("tomato", "gold", "darkolivegreen3", "forestgreen")) + 
#   scale_fill_manual(labels = c("All of them", "Most of them", "Some of them", "None"), 
#                       values = c("tomato", "gold", "darkolivegreen3", "forestgreen")) + 
#   guides(fill=guide_legend("Perceived\nCorruption")) +
#   theme_minimal()


data_clean <- na.omit(data)

# Isolate the relevant columns
isolated_data <- data_clean %>% select(Q38A, Q38B, Q38F)

# Reshape the data to long format
isolated_data_long <- isolated_data %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Value")


ggplot(isolated_data_long, aes(x = Category, fill = factor(Value))) +
  geom_bar(position = "stack") +
  labs(x = "Government Branches", y = "Count", title = "Distribution of Perceived Corruption in Mali Government Branches", fill = "Perceived Corruption") +
  scale_fill_manual(labels = c("3", "2", "1", "0"),
                      values = c("tomato", "gold", "darkolivegreen3", "forestgreen")) +
  scale_fill_manual(labels = c("All of them", "Most of them", "Some of them", "None"),
                      values = c("tomato", "gold", "darkolivegreen3", "forestgreen")) +
  # scale_fill_manual(
  #   values = c("forestgreen", "darkolivegreen3", "gold", "tomato"),
  #   labels = c("None", "Some of them", "Most of them", "All of them")) +
    scale_x_discrete(labels = c("Q38A" = "Executive", "Q38B" = "Legislative", "Q38F" = "Judicial")) +
  theme_minimal()

ggplot(isolated_data_long, aes(x = Category, fill = factor(Value))) +
  geom_bar(position = "stack") +
  labs(x = "Government Branches", y = "Count", title = "Distribution of Perceived Corruption in Mali Government Branches", fill = "Perceived Corruption") +
  scale_fill_manual(
    values = c("forestgreen", "darkolivegreen3", "gold", "tomato"),
    labels = c("None", "Some of them", "Most of them", "All of them")) +
    scale_x_discrete(labels = c("Q38A" = "Executive", "Q38B" = "Legislative", "Q38F" = "Judicial")) +
  theme_minimal()

```

## deprivation

```{r}
data$Q29B[data$Q6A == 9] <- NA
data$Q29B[data$Q6B == 9] <- NA
data$Q29B[data$Q6C == 9] <- NA
data$Q29B[data$Q6D == 9] <- NA
data$Q29B[data$Q6E == 9] <- NA

data$deprivation <- data$Q6A + data$Q6B + data$Q6C + data$Q6D + data$Q6E

depr_cols <- bind_cols(data$Q6A, data$Q6B, data$Q6C, data$Q6D, data$Q6E)
cronbach.alpha(depr_cols)

data %>%
  ggplot(aes(x = deprivation)) +
  geom_bar(fill = 'red4') +
  labs(title = "Deprivation Index Distribution of People in Mali 2022", 
       x = "Deprivation Index", 
       y = "Frequency")

length(data$deprivation)
length(data$deprivation[data$deprivation >=10 ])
```

## political instability

```{r}
table(data$vio_97_21)
```

## control

```{r}
# gender
unique(data$Q100)
data$Q100[data$Q100 == 2] <- 0
unique(data$Q100)

# age
data$Q1[data$Q1 == 999] <- NA

# education
data$Q94[data$Q94 == 99] <- NA
data$Q94[data$Q94 == -1] <- NA

# trust in military
data$Q37H[data$Q37H == 8] <- NA
data$Q37H[data$Q37H == 9] <- NA
data$Q37H[data$Q37H == -1] <- NA
```

## additional

ethnicity = Q84A
REGION

```{r}
# data$Q84A[data$Q84A > 2000] <- NA

data$REGION <- as.factor(data$REGION)
data$Q84A <- as.factor(data$Q84A)
```


```{r}
r7 <- lm(military ~ corrupt + deprivation + vio_97_21 + Q1 + Q37H + Q100 + Q94 + night_2020mean + REGION + Q84A, data = data)
summary(r7)
AIC(r7)
```
